#!/usr/bin/env python3
"""plistaddreg.py — register additional file extensions with app-router.

Adds the declarations needed for LaunchServices to let app-router become the
default handler for one or more file extensions, by editing the repo's:

    Sources/AppRouter/Info.plist

(resolved relative to this script, which lives in the repo's Scripts/ dir).

For each extension it adds a CFBundleDocumentTypes entry (so the app advertises
that it opens that type). The UTI it declares is resolved the SAME way the app
resolves it at runtime — `UTType(filenameExtension:)` — via a tiny Swift helper,
so the declaration always matches what the app looks up (see below). If macOS
already has a real (non-dynamic) system UTI for the extension (e.g. .css ->
public.css, .py -> public.python-script), that system UTI is declared. Only when
the OS has NO real type (a "dynamic" UTI, e.g. a bespoke ".foo") does the script
export its own UTI — "com.jsglazer.app-router.<ext>" tagged to that filename
extension — under UTExportedTypeDeclarations, the Apple-sanctioned way to claim
an otherwise-undeclared type.

Portability to other Macs: a real UTI on THIS Mac may come from a third-party
app rather than macOS itself (e.g. org.tug.tex is defined by TeXShop). On a Mac
without that app the extension would be dynamic and app-router would call it
unsupported. So any resolved UTI that macOS's own CoreTypes bundle does not
define is also declared under UTImportedTypeDeclarations (with its extension and
public.* parent types), which makes the type exist wherever app-router is
installed.

Why this matters: the app computes a file's type with UTType(filenameExtension:)
and only registers as default if its Info.plist declares THAT exact UTI. A
bespoke UTI declared for an extension macOS already owns (like .css) is silently
ignored, so the app would treat the extension as unsupported. Resolving the UTI
the same way the app does avoids that mismatch. If the Swift toolchain is
unavailable, the curated SYSTEM_UTI_EXTS map below is used as a fallback.

The edit is surgical: existing comments and formatting in Info.plist are kept.
Runs are idempotent — an extension already registered is skipped.

Usage:
    plistaddreg.py EXT [EXT ...]

    # extensions may be dot-prefixed and/or comma/space separated
    plistaddreg.py css
    plistaddreg.py foo, bar
    plistaddreg.py .less .scss stylus

After running, rebuild app-router and re-register it with LaunchServices
(rebuild + `lsregister` / relaunch) so the new types take effect. Only the
source Info.plist is edited; the built .app in dist/ is regenerated by a build.
"""

import os
import sys
import shutil
import plistlib
import subprocess
import tempfile

# This script lives in the repo's Scripts/ dir; resolve everything relative to it
# so it works wherever the repo is checked out (no hardcoded home path).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLIST = os.path.join(_REPO_ROOT, "Sources", "AppRouter", "Info.plist")

# Keep the backup OUTSIDE the Sources/ tree — a *.bak next to Info.plist makes
# SwiftPM warn about an unhandled resource in the target on every build. The repo
# root is not a build input, so the backup lives there instead.
BACKUP = os.path.join(_REPO_ROOT, "Info.plist.bak")

UTI_PREFIX = "com.jsglazer.app-router"

# UTIs the app treats as over-broad and refuses to register for (mirror of
# AppController.overBroadUTIs). If an extension resolves to one of these, we warn
# and fall back to a bespoke exported UTI rather than declaring a type the app
# will reject as unsupported.
OVERBROAD_UTIS = {
    "public.item", "public.content", "public.composite-content",
    "public.data", "public.text",
    "public.source-code", "public.script", "public.executable",
}

# Fallback map used only when the Swift resolver (resolve_system_utis) can't run.
# Normally the UTI is resolved dynamically with the same API the app uses, so
# this list does NOT need to be exhaustive — it's just a safety net for machines
# without a Swift toolchain. Entries here also override the dynamic result.
SYSTEM_UTI_EXTS = {
    "md": "net.daringfireball.markdown",
    "markdown": "net.daringfireball.markdown",
    "json": "public.json",
    "yaml": "public.yaml",
    "yml": "public.yaml",
    "xml": "public.xml",
    "html": "public.html",
    "htm": "public.html",
    "csv": "public.comma-separated-values-text",
    "pdf": "com.adobe.pdf",
    "svg": "public.svg-image",
    "rtf": "public.rtf",
    "txt": "public.plain-text",
    "sh": "public.shell-script",
}

# Where macOS defines its own (Apple-owned) UTIs. A UTI declared anywhere else
# belongs to a third-party app and must be imported to be portable.
CORETYPES = "/System/Library/CoreServices/CoreTypes.bundle"

TAB = "\t"

# Swift program that prints, per extension, the UTI the app would resolve at
# runtime and whether it is dynamic (i.e. macOS has no real system type for it).
# Output is one tab-separated line per (ext, candidate type), the preferred type
# first: "<ext>\t<identifier>\t<isDynamic>\t<comma-joined public.* supertypes>".
# The other candidates matter because which type a file gets can differ between
# Macs (e.g. .md is public.markdown or net.daringfireball.markdown).
_SWIFT_RESOLVER = (
    "import UniformTypeIdentifiers\n"
    "func row(_ e: String, _ t: UTType) {\n"
    "    let sup = t.supertypes.map(\\.identifier).filter { $0.hasPrefix(\"public.\") }.sorted().joined(separator: \",\")\n"
    "    print(\"\\(e)\\t\\(t.identifier)\\t\\(t.isDynamic)\\t\\(sup)\")\n"
    "}\n"
    "for e in CommandLine.arguments.dropFirst() {\n"
    "    guard let t = UTType(filenameExtension: e) else { print(\"\\(e)\\tNONE\\ttrue\\t\"); continue }\n"
    "    row(e, t)\n"
    "    for o in UTType.types(tag: e, tagClass: .filenameExtension, conformingTo: nil) where o != t { row(e, o) }\n"
    "}\n"
)


# public.* parents recorded per resolved UTI by resolve_system_utis(), used when
# writing an imported type declaration.
SUPERTYPES = {}

# Additional public.* types macOS (or an installed app) also maps to an ext,
# besides the preferred one — declared too so the app catches whichever one a
# given Mac assigns. Filled by resolve_system_utis().
EXTRA_UTIS = {}


def apple_defined_utis():
    """Every UTI macOS itself defines (CoreTypes.bundle and its nested bundles)."""
    utis = set()
    plists = [os.path.join(CORETYPES, "Contents", "Info.plist")]
    lib = os.path.join(CORETYPES, "Contents", "Library")
    if os.path.isdir(lib):
        for name in os.listdir(lib):
            plists.append(os.path.join(lib, name, "Contents", "Info.plist"))
    for path in plists:
        try:
            with open(path, "rb") as fh:
                data = plistlib.load(fh)
        except Exception:
            continue
        for key in ("UTExportedTypeDeclarations", "UTImportedTypeDeclarations"):
            for entry in data.get(key, []):
                ident = entry.get("UTTypeIdentifier")
                if ident:
                    utis.add(ident)
    return utis


def resolve_system_utis(exts):
    """Map each ext -> its real system UTI, or None when macOS has no real type.

    Uses `UTType(filenameExtension:)` via a Swift helper — the exact API the app
    uses at runtime — so declarations match what the app looks up. A dynamic
    (`dyn.*`) result means macOS has no real type, returned as None so the caller
    exports a bespoke UTI. Falls back to the curated map if Swift can't run.
    """
    swift = shutil.which("swift")
    if swift:
        path = None
        try:
            with tempfile.NamedTemporaryFile(
                    "w", suffix=".swift", delete=False) as fh:
                fh.write(_SWIFT_RESOLVER)
                path = fh.name
            proc = subprocess.run(
                [swift, path, *exts],
                capture_output=True, text=True, timeout=60)
            if proc.returncode == 0:
                result = {}
                for line in proc.stdout.splitlines():
                    parts = line.split("\t")
                    if len(parts) != 4:
                        continue
                    ext, ident, is_dynamic, sup = parts
                    real = is_dynamic != "true" and ident != "NONE"
                    if real:
                        SUPERTYPES[ident] = [x for x in sup.split(",") if x]
                    if ext not in result:
                        result[ext] = ident if real else None
                    elif real and ident.startswith("public.") \
                            and ident not in OVERBROAD_UTIS:
                        EXTRA_UTIS.setdefault(ext, []).append(ident)
                # Ensure every requested ext has an entry even if Swift skipped it.
                for ext in exts:
                    result.setdefault(ext, None)
                return result
            print("warning: Swift UTI resolver failed "
                  f"(exit {proc.returncode}); using curated fallback map",
                  file=sys.stderr)
        except Exception as exc:
            print(f"warning: Swift UTI resolver unavailable ({exc}); "
                  "using curated fallback map", file=sys.stderr)
        finally:
            if path and os.path.exists(path):
                os.unlink(path)
    else:
        print("warning: `swift` not found; using curated fallback map",
              file=sys.stderr)
    return {ext: SYSTEM_UTI_EXTS.get(ext) for ext in exts}


def normalize_exts(argv):
    """Turn raw argv into an ordered, de-duplicated list of clean extensions."""
    exts = []
    seen = set()
    for raw in argv:
        for piece in raw.replace(",", " ").split():
            ext = piece.strip().lstrip(".").lower()
            if not ext:
                continue
            if not all(c.isalnum() for c in ext):
                sys.exit(f"error: '{piece}' is not a valid extension "
                         "(letters/digits only)")
            if ext not in seen:
                seen.add(ext)
                exts.append(ext)
    return exts


def array_span(text, key):
    """Return (inner_start, close_start) for the <array> following <key>KEY</key>.

    inner_start is the offset just past the opening <array>; close_start is the
    offset of the matching (balanced) </array>. Handles nested arrays.
    """
    key_pos = text.find(f"<key>{key}</key>")
    if key_pos == -1:
        return None
    open_tag = text.find("<array>", key_pos)
    if open_tag == -1:
        return None
    i = open_tag
    depth = 0
    while True:
        na = text.find("<array>", i)
        ca = text.find("</array>", i)
        if ca == -1:
            raise ValueError("unbalanced <array> in plist")
        if na != -1 and na < ca:
            depth += 1
            i = na + len("<array>")
        else:
            depth -= 1
            i = ca + len("</array>")
            if depth == 0:
                return open_tag + len("<array>"), ca


def insert_before_close(text, close_pos, block):
    """Insert block at the start of the line that holds the closing tag."""
    line_start = text.rfind("\n", 0, close_pos) + 1
    return text[:line_start] + block + text[line_start:]


def doc_type_block(uti, name):
    return (
        f"{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}<key>CFBundleTypeName</key>\n"
        f"{TAB}{TAB}{TAB}<string>{name}</string>\n"
        f"{TAB}{TAB}{TAB}<key>CFBundleTypeRole</key>\n"
        f"{TAB}{TAB}{TAB}<string>Viewer</string>\n"
        f"{TAB}{TAB}{TAB}<key>LSHandlerRank</key>\n"
        f"{TAB}{TAB}{TAB}<string>Alternate</string>\n"
        f"{TAB}{TAB}{TAB}<key>LSItemContentTypes</key>\n"
        f"{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>{uti}</string>\n"
        f"{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}</dict>\n"
    )


def exported_type_block(ext, uti, name):
    return (
        f"{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeIdentifier</key>\n"
        f"{TAB}{TAB}{TAB}<string>{uti}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeDescription</key>\n"
        f"{TAB}{TAB}{TAB}<string>{name}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeConformsTo</key>\n"
        f"{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>public.data</string>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>public.content</string>\n"
        f"{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeTagSpecification</key>\n"
        f"{TAB}{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}{TAB}<key>public.filename-extension</key>\n"
        f"{TAB}{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}{TAB}<string>{ext}</string>\n"
        f"{TAB}{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}</dict>\n"
        f"{TAB}{TAB}</dict>\n"
    )


def imported_type_block(ext, uti, name, parents):
    conforms = "".join(
        f"{TAB}{TAB}{TAB}{TAB}<string>{p}</string>\n" for p in parents)
    return (
        f"{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeIdentifier</key>\n"
        f"{TAB}{TAB}{TAB}<string>{uti}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeDescription</key>\n"
        f"{TAB}{TAB}{TAB}<string>{name}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeConformsTo</key>\n"
        f"{TAB}{TAB}{TAB}<array>\n"
        f"{conforms}"
        f"{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeTagSpecification</key>\n"
        f"{TAB}{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}{TAB}<key>public.filename-extension</key>\n"
        f"{TAB}{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}{TAB}<string>{ext}</string>\n"
        f"{TAB}{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}</dict>\n"
        f"{TAB}{TAB}</dict>\n"
    )


def add_section_or_entries(text, key, blocks):
    """Append blocks to the <array> under KEY, creating the section if absent."""
    if not blocks:
        return text
    if f"<key>{key}</key>" in text:
        span = array_span(text, key)
        return insert_before_close(text, span[1], "".join(blocks))
    new_section = (
        f"{TAB}<key>{key}</key>\n"
        f"{TAB}<array>\n"
        f"{''.join(blocks)}"
        f"{TAB}</array>\n"
    )
    # Insert before the closing </dict> of the root plist dictionary.
    root_close = text.rfind("</dict>")
    line_start = text.rfind("\n", 0, root_close) + 1
    return text[:line_start] + new_section + text[line_start:]


def existing_state(data):
    """Collect the UTIs already advertised and extensions already exported."""
    doc_utis = set()
    for entry in data.get("CFBundleDocumentTypes", []):
        for uti in entry.get("LSItemContentTypes", []):
            doc_utis.add(uti)
    exported_exts = set()
    for entry in data.get("UTExportedTypeDeclarations", []):
        tags = entry.get("UTTypeTagSpecification", {})
        for e in tags.get("public.filename-extension", []):
            exported_exts.add(e.lower())
    imported_utis = {entry.get("UTTypeIdentifier")
                     for entry in data.get("UTImportedTypeDeclarations", [])}
    return doc_utis, exported_exts, imported_utis


def main(argv):
    exts = normalize_exts(argv)
    if not exts:
        sys.exit("usage: plistaddreg.py EXT [EXT ...]  (e.g. plistaddreg.py css foo bar)")

    if not os.path.isfile(PLIST):
        sys.exit(f"error: Info.plist not found at {PLIST}")

    with open(PLIST, "r", encoding="utf-8") as fh:
        text = fh.read()
    data = plistlib.loads(text.encode("utf-8"))

    doc_utis, exported_exts, imported_utis = existing_state(data)
    apple_utis = apple_defined_utis()

    # Resolve the real system UTI for each ext the way the app does; a curated
    # map entry (if any) overrides the dynamic result.
    resolved = resolve_system_utis(exts)

    doc_blocks = []          # new CFBundleDocumentTypes entries
    exported_blocks = []     # new UTExportedTypeDeclarations entries
    imported_blocks = []     # new UTImportedTypeDeclarations entries
    added, skipped = [], []

    for ext in exts:
        system_uti = SYSTEM_UTI_EXTS.get(ext) or resolved.get(ext)

        # An over-broad system type is one the app refuses to register for, so
        # fall back to a bespoke exported UTI (more specific) instead.
        if system_uti in OVERBROAD_UTIS:
            print(f"warning: .{ext} resolves to over-broad '{system_uti}'; "
                  "exporting a bespoke UTI instead", file=sys.stderr)
            system_uti = None

        export = system_uti is None
        name = f"{ext.upper()} Document"
        utis = [system_uti or f"{UTI_PREFIX}.{ext}"]
        if not export:
            utis += [u for u in EXTRA_UTIS.get(ext, []) if u not in utis]

        changed = False
        for uti in utis:
            # A real UTI that macOS itself doesn't define came from a third-party
            # app on this Mac; import it so the type also exists on Macs without
            # that app.
            needs_import = (not export and apple_utis
                            and not uti.startswith(UTI_PREFIX + ".")
                            and uti not in apple_utis and uti not in imported_utis)

            if (uti in doc_utis and not needs_import) or (export and ext in exported_exts):
                continue

            if uti not in doc_utis:
                doc_blocks.append(doc_type_block(uti, name))
                doc_utis.add(uti)
            if export:
                exported_blocks.append(exported_type_block(ext, uti, name))
                exported_exts.add(ext)
            kind = "exported UTI" if export else "system UTI"
            if needs_import:
                parents = SUPERTYPES.get(uti) or ["public.data", "public.content"]
                imported_blocks.append(imported_type_block(ext, uti, name, parents))
                imported_utis.add(uti)
                kind = "imported UTI (third-party type, declared for portability)"
            added.append((ext, uti, kind))
            changed = True
        if not changed:
            skipped.append(ext)

    if not doc_blocks and not imported_blocks:
        print("Nothing to do — all requested extensions are already registered:")
        for ext in skipped:
            print(f"  · .{ext}")
        return

    # 1) Insert new document-type dicts before the CFBundleDocumentTypes </array>.
    if doc_blocks:
        span = array_span(text, "CFBundleDocumentTypes")
        if span is None:
            sys.exit("error: CFBundleDocumentTypes array not found in plist")
        text = insert_before_close(text, span[1], "".join(doc_blocks))

    # 2) Insert / create the exported (bespoke) and imported (third-party) types.
    text = add_section_or_entries(text, "UTExportedTypeDeclarations", exported_blocks)
    text = add_section_or_entries(text, "UTImportedTypeDeclarations", imported_blocks)

    # Validate the result before touching disk; keep a backup either way.
    try:
        plistlib.loads(text.encode("utf-8"))
    except Exception as exc:  # pragma: no cover - safety net
        sys.exit(f"error: generated plist is invalid, aborting ({exc})")

    shutil.copy2(PLIST, BACKUP)
    with open(PLIST, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"Updated {PLIST}")
    print(f"(backup: {BACKUP})")
    for ext, uti, kind in added:
        print(f"  + .{ext:<10} -> {uti}  ({kind})")
    for ext in skipped:
        print(f"  · .{ext:<10} already registered, skipped")
    print("\nRebuild app-router and re-register with LaunchServices for the "
          "changes to take effect.")


if __name__ == "__main__":
    main(sys.argv[1:])
