#!/usr/bin/env python3
"""plistaddreg.py — register additional file extensions with app-router.

Adds the declarations needed for LaunchServices to let app-router become the
default handler for one or more file extensions, by editing the repo's:

    Sources/AppRouter/Info.plist

(resolved relative to this script, which lives in the repo's Scripts/ dir).

For each extension it adds a CFBundleDocumentTypes entry (so the app advertises
that it opens that type). The UTI it declares is resolved the SAME way the app
resolves it at runtime — `UTType(filenameExtension:)` — via a tiny Swift helper,
so the declaration always matches what the app looks up (see below). If macOS
already has a real (non-dynamic) system UTI for the extension (e.g. .css ->
public.css, .py -> public.python-script), that system UTI is declared. Only when
the OS has NO real type (a "dynamic" UTI, e.g. a bespoke ".foo") does the script
export its own UTI — "com.jsglazer.app-router.<ext>" tagged to that filename
extension — under UTExportedTypeDeclarations, the Apple-sanctioned way to claim
an otherwise-undeclared type.

Why this matters: the app computes a file's type with UTType(filenameExtension:)
and only registers as default if its Info.plist declares THAT exact UTI. A
bespoke UTI declared for an extension macOS already owns (like .css) is silently
ignored, so the app would treat the extension as unsupported. Resolving the UTI
the same way the app does avoids that mismatch. If the Swift toolchain is
unavailable, the curated SYSTEM_UTI_EXTS map below is used as a fallback.

The edit is surgical: existing comments and formatting in Info.plist are kept.
Runs are idempotent — an extension already registered is skipped.

Usage:
    plistaddreg.py EXT [EXT ...]

    # extensions may be dot-prefixed and/or comma/space separated
    plistaddreg.py css
    plistaddreg.py foo, bar
    plistaddreg.py .less .scss stylus

After running, rebuild app-router and re-register it with LaunchServices
(rebuild + `lsregister` / relaunch) so the new types take effect. Only the
source Info.plist is edited; the built .app in dist/ is regenerated by a build.
"""

import os
import sys
import shutil
import plistlib
import subprocess
import tempfile

# This script lives in the repo's Scripts/ dir; resolve everything relative to it
# so it works wherever the repo is checked out (no hardcoded home path).
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLIST = os.path.join(_REPO_ROOT, "Sources", "AppRouter", "Info.plist")

# Keep the backup OUTSIDE the Sources/ tree — a *.bak next to Info.plist makes
# SwiftPM warn about an unhandled resource in the target on every build. The repo
# root is not a build input, so the backup lives there instead.
BACKUP = os.path.join(_REPO_ROOT, "Info.plist.bak")

UTI_PREFIX = "com.jsglazer.app-router"

# UTIs the app treats as over-broad and refuses to register for (mirror of
# AppController.overBroadUTIs). If an extension resolves to one of these, we warn
# and fall back to a bespoke exported UTI rather than declaring a type the app
# will reject as unsupported.
OVERBROAD_UTIS = {
    "public.item", "public.content", "public.composite-content",
    "public.data", "public.text", "public.plain-text",
    "public.source-code", "public.script", "public.executable",
}

# Fallback map used only when the Swift resolver (resolve_system_utis) can't run.
# Normally the UTI is resolved dynamically with the same API the app uses, so
# this list does NOT need to be exhaustive — it's just a safety net for machines
# without a Swift toolchain. Entries here also override the dynamic result.
SYSTEM_UTI_EXTS = {
    "md": "net.daringfireball.markdown",
    "markdown": "net.daringfireball.markdown",
    "json": "public.json",
    "yaml": "public.yaml",
    "yml": "public.yaml",
    "xml": "public.xml",
    "html": "public.html",
    "htm": "public.html",
    "csv": "public.comma-separated-values-text",
    "pdf": "com.adobe.pdf",
    "svg": "public.svg-image",
    "rtf": "public.rtf",
}

TAB = "\t"

# Swift program that prints, per extension, the UTI the app would resolve at
# runtime and whether it is dynamic (i.e. macOS has no real system type for it).
# Output is one tab-separated line per ext: "<ext>\t<identifier>\t<isDynamic>".
_SWIFT_RESOLVER = (
    "import UniformTypeIdentifiers\n"
    "for e in CommandLine.arguments.dropFirst() {\n"
    "    if let t = UTType(filenameExtension: e) {\n"
    "        print(\"\\(e)\\t\\(t.identifier)\\t\\(t.isDynamic)\")\n"
    "    } else { print(\"\\(e)\\tNONE\\ttrue\") }\n"
    "}\n"
)


def resolve_system_utis(exts):
    """Map each ext -> its real system UTI, or None when macOS has no real type.

    Uses `UTType(filenameExtension:)` via a Swift helper — the exact API the app
    uses at runtime — so declarations match what the app looks up. A dynamic
    (`dyn.*`) result means macOS has no real type, returned as None so the caller
    exports a bespoke UTI. Falls back to the curated map if Swift can't run.
    """
    swift = shutil.which("swift")
    if swift:
        path = None
        try:
            with tempfile.NamedTemporaryFile(
                    "w", suffix=".swift", delete=False) as fh:
                fh.write(_SWIFT_RESOLVER)
                path = fh.name
            proc = subprocess.run(
                [swift, path, *exts],
                capture_output=True, text=True, timeout=60)
            if proc.returncode == 0:
                result = {}
                for line in proc.stdout.splitlines():
                    parts = line.split("\t")
                    if len(parts) != 3:
                        continue
                    ext, ident, is_dynamic = parts
                    result[ext] = (None if is_dynamic == "true"
                                   or ident == "NONE" else ident)
                # Ensure every requested ext has an entry even if Swift skipped it.
                for ext in exts:
                    result.setdefault(ext, None)
                return result
            print("warning: Swift UTI resolver failed "
                  f"(exit {proc.returncode}); using curated fallback map",
                  file=sys.stderr)
        except Exception as exc:
            print(f"warning: Swift UTI resolver unavailable ({exc}); "
                  "using curated fallback map", file=sys.stderr)
        finally:
            if path and os.path.exists(path):
                os.unlink(path)
    else:
        print("warning: `swift` not found; using curated fallback map",
              file=sys.stderr)
    return {ext: SYSTEM_UTI_EXTS.get(ext) for ext in exts}


def normalize_exts(argv):
    """Turn raw argv into an ordered, de-duplicated list of clean extensions."""
    exts = []
    seen = set()
    for raw in argv:
        for piece in raw.replace(",", " ").split():
            ext = piece.strip().lstrip(".").lower()
            if not ext:
                continue
            if not all(c.isalnum() for c in ext):
                sys.exit(f"error: '{piece}' is not a valid extension "
                         "(letters/digits only)")
            if ext not in seen:
                seen.add(ext)
                exts.append(ext)
    return exts


def array_span(text, key):
    """Return (inner_start, close_start) for the <array> following <key>KEY</key>.

    inner_start is the offset just past the opening <array>; close_start is the
    offset of the matching (balanced) </array>. Handles nested arrays.
    """
    key_pos = text.find(f"<key>{key}</key>")
    if key_pos == -1:
        return None
    open_tag = text.find("<array>", key_pos)
    if open_tag == -1:
        return None
    i = open_tag
    depth = 0
    while True:
        na = text.find("<array>", i)
        ca = text.find("</array>", i)
        if ca == -1:
            raise ValueError("unbalanced <array> in plist")
        if na != -1 and na < ca:
            depth += 1
            i = na + len("<array>")
        else:
            depth -= 1
            i = ca + len("</array>")
            if depth == 0:
                return open_tag + len("<array>"), ca


def insert_before_close(text, close_pos, block):
    """Insert block at the start of the line that holds the closing tag."""
    line_start = text.rfind("\n", 0, close_pos) + 1
    return text[:line_start] + block + text[line_start:]


def doc_type_block(uti, name):
    return (
        f"{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}<key>CFBundleTypeName</key>\n"
        f"{TAB}{TAB}{TAB}<string>{name}</string>\n"
        f"{TAB}{TAB}{TAB}<key>CFBundleTypeRole</key>\n"
        f"{TAB}{TAB}{TAB}<string>Viewer</string>\n"
        f"{TAB}{TAB}{TAB}<key>LSHandlerRank</key>\n"
        f"{TAB}{TAB}{TAB}<string>Alternate</string>\n"
        f"{TAB}{TAB}{TAB}<key>LSItemContentTypes</key>\n"
        f"{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>{uti}</string>\n"
        f"{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}</dict>\n"
    )


def exported_type_block(ext, uti, name):
    return (
        f"{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeIdentifier</key>\n"
        f"{TAB}{TAB}{TAB}<string>{uti}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeDescription</key>\n"
        f"{TAB}{TAB}{TAB}<string>{name}</string>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeConformsTo</key>\n"
        f"{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>public.data</string>\n"
        f"{TAB}{TAB}{TAB}{TAB}<string>public.content</string>\n"
        f"{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}<key>UTTypeTagSpecification</key>\n"
        f"{TAB}{TAB}{TAB}<dict>\n"
        f"{TAB}{TAB}{TAB}{TAB}<key>public.filename-extension</key>\n"
        f"{TAB}{TAB}{TAB}{TAB}<array>\n"
        f"{TAB}{TAB}{TAB}{TAB}{TAB}<string>{ext}</string>\n"
        f"{TAB}{TAB}{TAB}{TAB}</array>\n"
        f"{TAB}{TAB}{TAB}</dict>\n"
        f"{TAB}{TAB}</dict>\n"
    )


def existing_state(data):
    """Collect the UTIs already advertised and extensions already exported."""
    doc_utis = set()
    for entry in data.get("CFBundleDocumentTypes", []):
        for uti in entry.get("LSItemContentTypes", []):
            doc_utis.add(uti)
    exported_exts = set()
    for entry in data.get("UTExportedTypeDeclarations", []):
        tags = entry.get("UTTypeTagSpecification", {})
        for e in tags.get("public.filename-extension", []):
            exported_exts.add(e.lower())
    return doc_utis, exported_exts


def main(argv):
    exts = normalize_exts(argv)
    if not exts:
        sys.exit("usage: plistaddreg.py EXT [EXT ...]  (e.g. plistaddreg.py css foo bar)")

    if not os.path.isfile(PLIST):
        sys.exit(f"error: Info.plist not found at {PLIST}")

    with open(PLIST, "r", encoding="utf-8") as fh:
        text = fh.read()
    data = plistlib.loads(text.encode("utf-8"))

    doc_utis, exported_exts = existing_state(data)

    # Resolve the real system UTI for each ext the way the app does; a curated
    # map entry (if any) overrides the dynamic result.
    resolved = resolve_system_utis(exts)

    doc_blocks = []          # new CFBundleDocumentTypes entries
    exported_blocks = []     # new UTExportedTypeDeclarations entries
    added, skipped = [], []

    for ext in exts:
        system_uti = SYSTEM_UTI_EXTS.get(ext) or resolved.get(ext)

        # An over-broad system type is one the app refuses to register for, so
        # fall back to a bespoke exported UTI (more specific) instead.
        if system_uti in OVERBROAD_UTIS:
            print(f"warning: .{ext} resolves to over-broad '{system_uti}'; "
                  "exporting a bespoke UTI instead", file=sys.stderr)
            system_uti = None

        export = system_uti is None
        uti = system_uti or f"{UTI_PREFIX}.{ext}"
        name = f"{ext.upper()} Document"

        if uti in doc_utis or (export and ext in exported_exts):
            skipped.append(ext)
            continue

        doc_blocks.append(doc_type_block(uti, name))
        doc_utis.add(uti)
        if export:
            exported_blocks.append(exported_type_block(ext, uti, name))
            exported_exts.add(ext)
        added.append((ext, uti, export))

    if not doc_blocks:
        print("Nothing to do — all requested extensions are already registered:")
        for ext in skipped:
            print(f"  · .{ext}")
        return

    # 1) Insert new document-type dicts before the CFBundleDocumentTypes </array>.
    span = array_span(text, "CFBundleDocumentTypes")
    if span is None:
        sys.exit("error: CFBundleDocumentTypes array not found in plist")
    text = insert_before_close(text, span[1], "".join(doc_blocks))

    # 2) Insert / create UTExportedTypeDeclarations for the bespoke extensions.
    if exported_blocks:
        if "<key>UTExportedTypeDeclarations</key>" in text:
            span = array_span(text, "UTExportedTypeDeclarations")
            text = insert_before_close(text, span[1], "".join(exported_blocks))
        else:
            new_section = (
                f"{TAB}<key>UTExportedTypeDeclarations</key>\n"
                f"{TAB}<array>\n"
                f"{''.join(exported_blocks)}"
                f"{TAB}</array>\n"
            )
            # Insert before the closing </dict> of the root plist dictionary.
            root_close = text.rfind("</dict>")
            line_start = text.rfind("\n", 0, root_close) + 1
            text = text[:line_start] + new_section + text[line_start:]

    # Validate the result before touching disk; keep a backup either way.
    try:
        plistlib.loads(text.encode("utf-8"))
    except Exception as exc:  # pragma: no cover - safety net
        sys.exit(f"error: generated plist is invalid, aborting ({exc})")

    shutil.copy2(PLIST, BACKUP)
    with open(PLIST, "w", encoding="utf-8") as fh:
        fh.write(text)

    print(f"Updated {PLIST}")
    print(f"(backup: {BACKUP})")
    for ext, uti, export in added:
        kind = "exported UTI" if export else "system UTI"
        print(f"  + .{ext:<10} -> {uti}  ({kind})")
    for ext in skipped:
        print(f"  · .{ext:<10} already registered, skipped")
    print("\nRebuild app-router and re-register with LaunchServices for the "
          "changes to take effect.")


if __name__ == "__main__":
    main(sys.argv[1:])
